# DZMQ
language: d

#compiler:
#  - dmd

install:
  # dmd
  # dub
  - DMD_VER=2.066.0
  - DMD=dmd_${DMD_VER}-0_amd64.deb
  - DUB_VER=0.9.21
  - DUB=dub-${DUB_VER}-linux-x86_64
  - wget http://downloads.dlang.org/releases/2014/${DMD}
  - sudo dpkg -i ${DMD} || true
  - sudo apt-get -y update || true
  - sudo apt-get -fy install || true
  - sudo dpkg -i ${DMD}
  - wget http://code.dlang.org/files/${DUB}.tar.gz
  - sudo tar -C /usr/local/bin -zxf ${DUB}.tar.gz

before_script:
  # Install libsodium for curve related test
  - git clone git://github.com/jedisct1/libsodium.git
  - cd libsodium
  - ./autogen.sh
  - ./configure && make -j4
  - sudo make install
  - sudo ldconfig
  - cd ..

  # Perform regression test build against ZeroMQ v4.x
  - git clone git://github.com/zeromq/zeromq4-x.git
  - cd zeromq4-x
  - ./autogen.sh
  - ./configure && make -j4
  - sudo make install
  - sudo ldconfig
  - cd ..

script:
  - dub test

